trigger: none

pool:
  name: ALZ-AgentPool

steps:

- script: echo "Hello Surendra, Azure DevOps Pipeline Working Fine!"
  displayName: 'Print Message'

- script: |
    echo "Checking Terraform Version"
    terraform version
  displayName: 'Terraform Version Check'

- script: |
    echo "Listing Files"
    dir
  displayName: 'List Files'